name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests
        run: echo "No tests yet" && exit 0

      - name: Build de l'app
        run: npm run build

      - name: Configurer Git
        run: |
          git config user.name "DJOUMESSI2004"
          git config user.email "wilfridndongmo@gmail.com"

      - name: Déployer sur GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}